#!/usr/bin/env python3
"""Render Asterisk .conf files from the data/config.json file.

Asterisk has no native JSON support; it reads .conf files. This script is run
by the container entrypoint at startup. It reads the user-facing config.json,
validates it, and writes pjsip.conf / extensions.conf / voicemail.conf /
rtp.conf / asterisk.conf / logger.conf into the Asterisk config directory.

Usage: render_config.py <config.json> <output_dir>
"""

import json
import sys
import urllib.request


def fail(msg):
    print(f"[render_config] ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def detect_external_ip():
    for url in ("https://api.ipify.org", "https://ifconfig.me/ip"):
        try:
            with urllib.request.urlopen(url, timeout=5) as r:
                ip = r.read().decode().strip()
                if ip:
                    return ip
        except Exception:
            continue
    return None


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def load_and_validate(path):
    try:
        with open(path) as f:
            cfg = json.load(f)
    except FileNotFoundError:
        fail(f"config file not found: {path}")
    except json.JSONDecodeError as e:
        fail(f"config.json is not valid JSON: {e}")

    trunk = cfg.get("trunk")
    if not trunk:
        fail("missing 'trunk' section")
    for key in ("server", "username", "password", "did"):
        if not trunk.get(key):
            fail(f"trunk.{key} is required")

    if trunk.get("encryption"):
        host = str(trunk["server"]).split(".")[0]
        if not host[-1:].isdigit():
            print(f"[render_config] WARNING: trunk.encryption is on but server "
                  f"'{trunk['server']}' is not a numbered host. Some SIP trunk "
                  f"providers require a numbered hostname for TLS (e.g. sip1.example.com), "
                  f"or registration will fail.", file=sys.stderr)

    exts = cfg.get("extensions")
    if not exts:
        fail("at least one entry in 'extensions' is required")
    seen = set()
    for e in exts:
        eid = str(e.get("id", "")).strip()
        if not eid:
            fail("every extension needs an 'id'")
        if not e.get("password"):
            fail(f"extension {eid} needs a 'password'")
        if eid in seen:
            fail(f"duplicate extension id: {eid}")
        seen.add(eid)

    inbound = str(cfg.get("inbound_extension") or exts[0]["id"])
    if inbound not in seen:
        fail(f"inbound_extension '{inbound}' is not a defined extension")
    cfg["inbound_extension"] = inbound

    cfg.setdefault("blocklist", [])
    cfg.setdefault("sms", {"enabled": False})
    lg = cfg.setdefault("logging", {})
    lg.setdefault("calls", True)
    lg.setdefault("messages", True)
    s = cfg.setdefault("settings", {})
    s.setdefault("codecs", ["ulaw", "alaw"])
    s.setdefault("rtp_start", 10000)
    s.setdefault("rtp_end", 10100)
    s.setdefault("external_ip", "auto")
    s.setdefault("timezone", "America/New_York")
    # Encrypt the client/extension leg too (SIP-TLS on 5061 + mandatory SRTP).
    # Independent of trunk.encryption, which only covers the trunk leg.
    s.setdefault("client_encryption", False)
    return cfg


# ---------------------------------------------------------------------------
# File renderers
# ---------------------------------------------------------------------------

def render_asterisk_conf():
    # Override ONLY the directories that must live on the mounted /data volume so
    # they survive container restarts/rebuilds: the AstDB (call-forward *72/*73
    # state), the voicemail spool, and the logs (CDR call log + messages). Any
    # directive omitted here keeps Asterisk's compiled-in default, which is what we
    # want for the rest -- astmoddir and astdatadir in particular are distro paths
    # (Ubuntu: a multiarch module dir, and /usr/share/asterisk for the XML docs /
    # sounds / keys). Hardcoding those wrong breaks startup: a misdirected
    # astdatadir hides core-en_US.xml and Asterisk dies with "Stasis
    # initialization failed". Earlier this whole section was a never-applied
    # template ([directories](!)), so those wrong values silently did nothing and
    # everything quietly used the real defaults -- but that also meant astlogdir/
    # astspooldir/astdbdir were ignored, so CDRs/voicemail/AstDB wrote to ephemeral
    # in-container paths and were lost on restart.
    return """; GENERATED by render_config.py - do not edit by hand.
[directories]
astdbdir => /data/db
astspooldir => /data/spool
astlogdir => /data/logs

[options]
runuser = root
rungroup = root
"""


def render_modules_conf():
    # autoload everything; the PJSIP stack, app_voicemail, app_mixmonitor and
    # res_pjsip_messaging all load automatically. chan_sip is gone in v20.
    # autoload everything, but skip the Lua/AEL dialplan engines: we only use
    # pbx_config (.conf dialplan), and they otherwise load demo/default
    # contexts we don't want on an internet-facing PBX.
    # We log calls as JSON via cdr_custom; disable cdr_csv so we don't also get a
    # parallel Master.csv we never read.
    # Ubuntu's asterisk-modules ships BOTH app_voicemail.so (file storage) and
    # app_voicemail_imap.so (IMAP storage). With autoload the IMAP variant wins
    # the race, registers VoiceMail/VoiceMailMain, and the file-based module then
    # declines ("Already have an application 'VoiceMail'"). We use file storage
    # (voicemail.conf + /data/spool/voicemail), so noload the IMAP build to let
    # the file-based app_voicemail.so load. app_voicemail_odbc.so is the same
    # collision (no ODBC configured, so it declines anyway) -- noload it too to
    # keep the boot logs clean and unambiguous about which module owns voicemail.
    return """; GENERATED by render_config.py
[modules]
autoload=yes
noload=pbx_lua.so
noload=pbx_ael.so
noload=cdr_csv.so
noload=app_voicemail_imap.so
noload=app_voicemail_odbc.so
"""


def render_logger_conf():
    return """; GENERATED by render_config.py
[general]

[logfiles]
console => notice,warning,error
messages => notice,warning,error,verbose
"""


def render_rtp_conf(s):
    return (
        "; GENERATED by render_config.py\n"
        "[general]\n"
        f"rtpstart={s['rtp_start']}\n"
        f"rtpend={s['rtp_end']}\n"
    )


def render_cdr_conf(cfg):
    # CDR drives the JSON call log (via cdr_custom). unanswered/congestion=yes so
    # missed and failed calls are logged too, not just answered ones.
    if not cfg["logging"].get("calls", True):
        return "; GENERATED by render_config.py\n[general]\nenable=no\n"
    return (
        "; GENERATED by render_config.py\n"
        "[general]\n"
        "enable=yes\n"
        "unanswered=yes\n"
        "congestion=yes\n"
    )


def render_cdr_custom_conf(cfg):
    # One JSON object per line (JSONL) -> /data/logs/cdr-custom/calls.jsonl.
    # cdr_custom substitutes ${CDR(...)} at hangup; the path is fixed by Asterisk
    # to <astlogdir>/cdr-custom/. 'direction' and 'recording' are custom CDR
    # fields we Set() in the dialplan.
    fields = (
        '{'
        '"start":"${CDR(start)}",'
        '"answer":"${CDR(answer)}",'
        '"end":"${CDR(end)}",'
        '"direction":"${CDR(direction)}",'
        '"src":"${CDR(src)}",'
        '"dst":"${CDR(dst)}",'
        '"duration":${IF($[${LEN(${CDR(duration)})}>0]?${CDR(duration)}:0)},'
        '"billsec":${IF($[${LEN(${CDR(billsec)})}>0]?${CDR(billsec)}:0)},'
        '"disposition":"${CDR(disposition)}",'
        '"recording":"${CDR(recording)}",'
        '"uniqueid":"${CDR(uniqueid)}"'
        '}'
    )
    return (
        "; GENERATED by render_config.py\n"
        "[mappings]\n"
        f"calls.jsonl => {fields}\n"
    )


def render_pjsip_conf(cfg, external_ip):
    s = cfg["settings"]
    trunk = cfg["trunk"]
    codecs = ",".join(s["codecs"])
    sms_on = bool(cfg["sms"].get("enabled"))

    # Trunk-only encryption: SIP-TLS + SRTP to the trunk provider. The client
    # (extension) leg stays on plain UDP. Providers that support encryption
    # typically require TLS on port 5061 and mandatory SRTP, and may require the
    # server hostname in a numbered form (e.g. sip1.example.com).
    tls = bool(trunk.get("encryption"))
    trunk_transport = "transport-tls" if tls else "transport-udp"
    server_uri = f"sip:{trunk['server']}:5061" if tls else f"sip:{trunk['server']}"

    # Client-leg encryption: extensions register over TLS (5061) and use SRTP.
    # Needs the shared [transport-tls] to also carry a server certificate so
    # Asterisk can accept inbound TLS from the phones (the entrypoint generates a
    # self-signed cert under /data/certs when this is on).
    client_tls = bool(s.get("client_encryption"))
    need_tls = tls or client_tls
    ext_transport = "transport-tls" if client_tls else "transport-udp"

    out = ["; GENERATED by render_config.py - edit data/config.json instead.\n"]

    # ---- transports ----
    out.append("[transport-udp]")
    out.append("type=transport")
    out.append("protocol=udp")
    out.append("bind=0.0.0.0")
    out.append("local_net=10.0.0.0/8")
    out.append("local_net=172.16.0.0/12")
    out.append("local_net=192.168.0.0/16")
    if external_ip:
        out.append(f"external_media_address={external_ip}")
        out.append(f"external_signaling_address={external_ip}")
    out.append("")

    if need_tls:
        out.append("[transport-tls]")
        out.append("type=transport")
        out.append("protocol=tls")
        out.append("bind=0.0.0.0:5061")
        out.append("local_net=10.0.0.0/8")
        out.append("local_net=172.16.0.0/12")
        out.append("local_net=192.168.0.0/16")
        if external_ip:
            out.append(f"external_media_address={external_ip}")
            out.append(f"external_signaling_address={external_ip}")
        out.append("method=tlsv1_2")
        if client_tls:
            # Server cert so Asterisk can accept TLS from the SIP clients. Clients
            # still authenticate with SIP digest auth, so we don't require client
            # certs (no verify_client). The cert is self-signed by the entrypoint.
            out.append("cert_file=/data/certs/asterisk.crt")
            out.append("priv_key_file=/data/certs/asterisk.key")
        if tls and trunk.get("tls_verify", True):
            # Verify the trunk provider's server certificate against the system CA bundle
            # (only relevant for the outbound trunk leg, not the client leg).
            out.append("verify_server=yes")
            out.append("ca_list_file=/etc/ssl/certs/ca-certificates.crt")
        out.append("")

    # ---- SIP trunk ----
    out.append("[trunk_auth]")
    out.append("type=auth")
    out.append("auth_type=userpass")
    out.append(f"username={trunk['username']}")
    out.append(f"password={trunk['password']}")
    out.append("")

    out.append("[trunk_aor]")
    out.append("type=aor")
    out.append(f"contact={server_uri}")
    out.append("qualify_frequency=60")
    out.append("")

    if trunk.get("register", True):
        out.append("[trunk_reg]")
        out.append("type=registration")
        out.append(f"transport={trunk_transport}")
        out.append("outbound_auth=trunk_auth")
        out.append(f"server_uri={server_uri}")
        out.append(f"client_uri=sip:{trunk['username']}@{trunk['server']}")
        out.append("retry_interval=60")
        out.append("forbidden_retry_interval=300")
        out.append("expiration=3600")
        out.append("")

    out.append("[trunk_endpoint]")
    out.append("type=endpoint")
    out.append(f"transport={trunk_transport}")
    out.append("context=from-trunk")
    out.append("disallow=all")
    out.append(f"allow={codecs}")
    out.append("outbound_auth=trunk_auth")
    out.append("aors=trunk_aor")
    out.append(f"from_user={trunk['username']}")
    out.append(f"from_domain={trunk['server']}")
    out.append("direct_media=no")
    out.append("rtp_symmetric=yes")
    out.append("force_rport=yes")
    out.append("rewrite_contact=yes")
    if tls:
        # Mandatory SRTP (encrypted trunks reject with SIP 488 otherwise).
        out.append("media_encryption=sdes")
        out.append("media_encryption_optimistic=no")
    if sms_on:
        out.append("message_context=sms-in")
    out.append("")

    out.append("[trunk_identify]")
    out.append("type=identify")
    out.append("endpoint=trunk_endpoint")
    out.append(f"match={trunk['server']}")
    out.append("")

    # ---- extensions ----
    for e in cfg["extensions"]:
        eid = str(e["id"])
        rec_on = bool(e.get("call_recording", {}).get("enabled"))
        vm_on = bool(e.get("voicemail", {}).get("enabled"))

        out.append(f"[{eid}]")
        out.append("type=endpoint")
        out.append(f"transport={ext_transport}")
        out.append("context=from-internal")
        out.append("disallow=all")
        out.append(f"allow={codecs}")
        out.append(f"auth={eid}_auth")
        # The AOR must be named after the extension id (== the username the client
        # registers with): Asterisk's registrar matches the REGISTER's To-user
        # against the endpoint's AOR names, so a mismatched name (e.g. "1001_aor")
        # makes registration fail with "AOR '' not found" / 404.
        out.append(f"aors={eid}")
        # Extensions are remote SIP clients (mobile phones) that are virtually
        # always behind NAT. Without these, Asterisk stores the client's PRIVATE
        # Contact address from the REGISTER and then sends inbound INVITEs/RTP to
        # that unreachable address — so incoming calls never arrive on the phone.
        # rewrite_contact rebinds the Contact to the real source ip:port of the
        # registration (the NAT pinhole the app keep-alive holds open).
        out.append("rewrite_contact=yes")
        out.append("force_rport=yes")
        out.append("rtp_symmetric=yes")
        out.append("direct_media=no")
        if client_tls:
            # Mandatory SRTP for the media leg, matching the app's config. The
            # SDES keys ride inside the TLS-encrypted SDP, never in plaintext.
            out.append("media_encryption=sdes")
            out.append("media_encryption_optimistic=no")
        if e.get("callerid"):
            out.append(f"callerid={e['callerid']}")
        if vm_on:
            out.append(f"mailboxes={eid}@default")
        out.append(f"set_var=EXTID={eid}")
        out.append(f"set_var=EXTREC={'1' if rec_on else '0'}")
        if sms_on:
            out.append("message_context=sms-out")
        out.append("")

        out.append(f"[{eid}_auth]")
        out.append("type=auth")
        out.append("auth_type=userpass")
        out.append(f"username={eid}")
        out.append(f"password={e['password']}")
        out.append("")

        out.append(f"[{eid}]")
        out.append("type=aor")
        out.append("max_contacts=1")
        out.append("remove_existing=yes")
        out.append("")

    return "\n".join(out) + "\n"


def render_voicemail_conf(cfg):
    ext_ip = cfg.get("settings", {}).get("external_ip")
    # Voicemail is retrieval-only (dial-in via VoiceMailMain) -- no email
    # delivery, so we omit attach/emailsubject and leave the per-mailbox email
    # field blank. Messages live under /data/spool/voicemail.
    out = [
        "; GENERATED by render_config.py",
        "[general]",
        "format=wav49|wav",
        "maxmsg=100",
        "maxsecs=300",
        "minsecs=2",
        "",
        "[default]",
    ]
    for e in cfg["extensions"]:
        vm = e.get("voicemail", {})
        if not vm.get("enabled"):
            continue
        eid = str(e["id"])
        pin = str(vm.get("pin", "0000"))
        name = (e.get("callerid") or eid).split("<")[0].strip().strip('"') or eid
        # mailbox => PIN,Name  (no email -> Asterisk sends no notification)
        out.append(f"{eid} => {pin},{name}")
    return "\n".join(out) + "\n"


def render_extensions_conf(cfg):
    trunk = cfg["trunk"]
    did = trunk["did"]
    blocklist = [str(n).strip() for n in cfg["blocklist"] if str(n).strip()]
    inbound_id = cfg["inbound_extension"]
    sms_on = bool(cfg["sms"].get("enabled"))
    msg_log = bool(cfg["logging"].get("messages", True))

    inbound_ext = next(e for e in cfg["extensions"] if str(e["id"]) == inbound_id)
    in_rec = bool(inbound_ext.get("call_recording", {}).get("enabled"))
    in_vm = bool(inbound_ext.get("voicemail", {}).get("enabled"))
    fwd = inbound_ext.get("call_forward", {})
    fwd_on = bool(fwd.get("enabled"))
    fwd_dest = str(fwd.get("destination", "")).strip()
    if fwd_on and not fwd_dest:
        fail(f"extension {inbound_id}: call_forward enabled but no destination")

    L = ["; GENERATED by render_config.py - edit data/config.json instead.\n"]

    L.append("[globals]")
    L.append("REC_DIR=/data/recordings")
    L.append(f"TRUNK_DID={did}")
    L.append("")

    # ---- block list subroutine ----
    # Called as Gosub(blocklist-check,<number>,1). Hangs up on a match,
    # returns otherwise so the caller continues.
    L.append("[blocklist-check]")
    for n in blocklist:
        L.append(f"exten => {n},1,Verbose(1,Blocked number {n})")
        L.append(" same => n,Hangup()")
    L.append("exten => _.,1,Return()")
    L.append("exten => s,1,Return()")
    L.append("")

    # ---- inbound (calls arriving from the trunk) ----
    L.append("[from-trunk]")
    L.append("exten => _.,1,NoOp(Inbound call from ${CALLERID(num)} to ${EXTEN})")
    L.append(" same => n,Set(CDR(direction)=inbound)")
    L.append(" same => n,Gosub(blocklist-check,${CALLERID(num)},1)")
    if in_rec:
        L.append(" same => n,Set(RECFILE=${REC_DIR}/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-in-${CALLERID(num)}.wav)")
        L.append(" same => n,MixMonitor(${RECFILE})")
        L.append(" same => n,Set(CDR(recording)=${RECFILE})")
    # Call forwarding. A runtime override set from a phone via *72/*73 lives in
    # AstDB (CFWD/<ext>) and wins over the config default; "off" means a *73
    # explicitly disabled it. Empty => ring the extension locally.
    cfg_default = fwd_dest if fwd_on else ""
    L.append(f" same => n,Set(FWD=${{DB(CFWD/{inbound_id})}})")
    L.append(f" same => n,ExecIf($[\"${{FWD}}\" = \"\"]?Set(FWD={cfg_default}))")
    L.append(" same => n,ExecIf($[\"${FWD}\" = \"off\"]?Set(FWD=))")
    L.append(f" same => n,Set(DIALTARGET=PJSIP/{inbound_id})")
    L.append(" same => n,Set(DIALTMO=25)")
    L.append(" same => n,ExecIf($[\"${FWD}\" != \"\"]?Set(DIALTARGET=PJSIP/${FWD}@trunk_endpoint))")
    L.append(" same => n,ExecIf($[\"${FWD}\" != \"\"]?Set(DIALTMO=40))")
    L.append(" same => n,ExecIf($[\"${FWD}\" != \"\"]?NoOp(Forwarding to ${FWD}))")
    L.append(" same => n,Dial(${DIALTARGET},${DIALTMO})")
    if in_vm:
        L.append(f" same => n,Goto(voicemail,{inbound_id},1)")
    L.append(" same => n,Hangup()")
    L.append("")

    # ---- voicemail deposit ----
    L.append("[voicemail]")
    for e in cfg["extensions"]:
        if e.get("voicemail", {}).get("enabled"):
            eid = str(e["id"])
            L.append(f"exten => {eid},1,VoiceMail({eid}@default,u)")
            L.append(" same => n,Hangup()")
    L.append("")

    # ---- internal / outbound ----
    L.append("[from-internal]")
    # extension-to-extension dialing (honors a *72/*73 forward override on the
    # dialed extension; "off" or unset rings the extension locally)
    for e in cfg["extensions"]:
        eid = str(e["id"])
        callee_rec = bool(e.get("call_recording", {}).get("enabled"))
        L.append(f"exten => {eid},1,Set(CDR(direction)=internal)")
        L.append(f" same => n,Set(FWD=${{DB(CFWD/{eid})}})")
        L.append(" same => n,ExecIf($[\"${FWD}\" = \"off\"]?Set(FWD=))")
        L.append(" same => n,GotoIf($[\"${FWD}\" != \"\"]?fwd)")
        # Record the internal leg when EITHER party wants it: INTREC is '1' if the
        # called extension always records (render-time), otherwise it falls back to
        # the caller's EXTREC channel var. MixMonitor on the local ring path only;
        # the forwarded-to-trunk path below is recorded like any outbound call.
        L.append(f" same => n,Set(INTREC={'1' if callee_rec else '${EXTREC}'})")
        L.append(" same => n,ExecIf($[\"${INTREC}\" = \"1\"]?Set(RECFILE=${REC_DIR}/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-int-${EXTID}-" + eid + ".wav))")
        L.append(" same => n,ExecIf($[\"${INTREC}\" = \"1\"]?MixMonitor(${RECFILE}))")
        L.append(" same => n,ExecIf($[\"${INTREC}\" = \"1\"]?Set(CDR(recording)=${RECFILE}))")
        L.append(f" same => n,Dial(PJSIP/{eid},30)")
        if e.get("voicemail", {}).get("enabled"):
            L.append(f" same => n,Goto(voicemail,{eid},1)")
        L.append(" same => n,Hangup()")
        L.append(" same => n(fwd),Set(CDR(direction)=outbound)")
        L.append(" same => n,NoOp(Forwarding ${EXTEN} to ${FWD})")
        L.append(" same => n,Set(CALLERID(num)=${TRUNK_DID})")
        L.append(" same => n,Dial(PJSIP/${FWD}@trunk_endpoint,40)")
        L.append(" same => n,Hangup()")
    # voicemail access
    L.append("exten => *97,1,VoiceMailMain(${EXTID}@default)")
    L.append(" same => n,Hangup()")
    # call forwarding: *72<number> enables, *73 disables (per calling extension)
    L.append("exten => _*72.,1,Set(DB(CFWD/${EXTID})=${EXTEN:3})")
    L.append(" same => n,Answer()")
    L.append(" same => n,Playback(call-fwd-unconditional&activated)")
    L.append(" same => n,Hangup()")
    L.append("exten => *73,1,Set(DB(CFWD/${EXTID})=off)")
    L.append(" same => n,Answer()")
    L.append(" same => n,Playback(call-fwd-unconditional&de-activated)")
    L.append(" same => n,Hangup()")
    # outbound to PSTN (10- or 11-digit North American)
    for pat in ("_1NXXNXXXXXX", "_NXXNXXXXXX", "_011.", "_NXXXXXX"):
        L.append(f"exten => {pat},1,NoOp(Outbound call to ${{EXTEN}})")
        L.append(" same => n,Set(CDR(direction)=outbound)")
        L.append(" same => n,Gosub(blocklist-check,${EXTEN},1)")
        L.append(" same => n,ExecIf($[\"${EXTREC}\" = \"1\"]?Set(RECFILE=${REC_DIR}/${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-out-${EXTID}-${EXTEN}.wav))")
        L.append(" same => n,ExecIf($[\"${EXTREC}\" = \"1\"]?MixMonitor(${RECFILE}))")
        L.append(" same => n,ExecIf($[\"${EXTREC}\" = \"1\"]?Set(CDR(recording)=${RECFILE}))")
        L.append(f" same => n,Set(CALLERID(num)=${{TRUNK_DID}})")
        L.append(" same => n,Dial(PJSIP/${EXTEN}@trunk_endpoint,60)")
        L.append(" same => n,Hangup()")
    L.append("")

    # ---- SMS over SIP MESSAGE (best-effort; SMS only, not MMS) ----
    if sms_on:
        # Free-text/number fields are base64-encoded and single-quoted before they
        # reach the shell, so a message body can't break word-splitting or inject
        # anything into the System() command line. log_msg.py decodes them.
        msglog = "/data/logs/messages.jsonl"
        L.append("[sms-in]")
        L.append("exten => _.,1,NoOp(Inbound SMS from ${MESSAGE(from)})")
        L.append(" same => n,Set(SMSFROM=${CUT(CUT(MESSAGE(from),@,1),:,2)})")
        L.append(" same => n,Gosub(blocklist-check,${SMSFROM},1)")
        if msg_log:
            L.append(f" same => n,System(/opt/reelhelm/log_msg.py '{msglog}' 'in' "
                     "'${BASE64_ENCODE(${SMSFROM})}' '${BASE64_ENCODE(${TRUNK_DID})}' "
                     "'${BASE64_ENCODE(${MESSAGE(body)})}')")
        L.append(f" same => n,MessageSend(pjsip:{inbound_id},${{SMSFROM}})")
        L.append(" same => n,Hangup()")
        L.append("")
        L.append("[sms-out]")
        # Local extension-to-extension delivery. A SIP MESSAGE whose target user
        # is a known local extension is handed straight to that endpoint, keeping
        # the real sender extension as the From (so the recipient threads it under
        # the sender, not the trunk DID). The target user part is the dialplan
        # EXTEN here, so a literal pattern per extension matches it directly and
        # takes priority over the _. PSTN catch-all below.
        for e in cfg["extensions"]:
            peer = str(e["id"])
            L.append(f"exten => {peer},1,NoOp(Local SMS to {peer} from ${{MESSAGE(from)}})")
            L.append(" same => n,Set(SMSFROM=${CUT(CUT(MESSAGE(from),@,1),:,2)})")
            if msg_log:
                L.append(f" same => n,System(/opt/reelhelm/log_msg.py '{msglog}' 'local' "
                         "'${BASE64_ENCODE(${SMSFROM})}' "
                         f"'${{BASE64_ENCODE({peer})}}' "
                         "'${BASE64_ENCODE(${MESSAGE(body)})}')")
            L.append(f" same => n,MessageSend(pjsip:{peer},${{SMSFROM}})")
            L.append(" same => n,Hangup()")
        # PSTN: anything that isn't a local extension goes out the trunk, with the
        # From rewritten to the trunk DID so the carrier accepts it.
        L.append("exten => _.,1,NoOp(Outbound SMS to ${MESSAGE(to)})")
        L.append(" same => n,Set(DEST=${CUT(CUT(MESSAGE(to),@,1),:,2)})")
        if msg_log:
            L.append(f" same => n,System(/opt/reelhelm/log_msg.py '{msglog}' 'out' "
                     "'${BASE64_ENCODE(${TRUNK_DID})}' '${BASE64_ENCODE(${DEST})}' "
                     "'${BASE64_ENCODE(${MESSAGE(body)})}')")
        L.append(f" same => n,Set(MESSAGE(from)=sip:${{TRUNK_DID}}@{trunk['server']})")
        L.append(" same => n,MessageSend(pjsip:${DEST}@trunk_endpoint,${TRUNK_DID})")
        L.append(" same => n,Hangup()")
        L.append("")

    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) != 3:
        fail("usage: render_config.py <config.json> <output_dir>")
    cfg_path, out_dir = sys.argv[1], sys.argv[2]
    cfg = load_and_validate(cfg_path)

    s = cfg["settings"]
    external_ip = None
    want_ip = s.get("external_ip", "auto")
    if want_ip == "auto":
        external_ip = detect_external_ip()
        if external_ip:
            print(f"[render_config] detected external IP: {external_ip}")
        else:
            print("[render_config] WARNING: could not auto-detect external IP; "
                  "NAT traversal may be incomplete. Set settings.external_ip "
                  "manually if calls have one-way/no audio.", file=sys.stderr)
    elif want_ip:
        external_ip = want_ip

    files = {
        "asterisk.conf": render_asterisk_conf(),
        "modules.conf": render_modules_conf(),
        "logger.conf": render_logger_conf(),
        "rtp.conf": render_rtp_conf(s),
        "cdr.conf": render_cdr_conf(cfg),
        "pjsip.conf": render_pjsip_conf(cfg, external_ip),
        "voicemail.conf": render_voicemail_conf(cfg),
        "extensions.conf": render_extensions_conf(cfg),
    }
    if cfg["logging"].get("calls", True):
        files["cdr_custom.conf"] = render_cdr_custom_conf(cfg)
    for name, content in files.items():
        path = f"{out_dir.rstrip('/')}/{name}"
        with open(path, "w") as f:
            f.write(content)
        print(f"[render_config] wrote {path}")

    print(f"[render_config] OK: {len(cfg['extensions'])} extension(s), "
          f"{len(cfg['blocklist'])} blocked number(s), "
          f"SMS {'on' if cfg['sms'].get('enabled') else 'off'}")


if __name__ == "__main__":
    main()
